# 250610 화 PM 7:38

WITH
    t1 AS (
    SELECT
        HOUR(datetime) AS hour,
        COUNT(*) AS count
    FROM animal_outs
    GROUP BY hour
    ),
    
    t2 AS (
    (SELECT 0 AS HOUR) UNION (SELECT 1 AS HOUR) UNION (SELECT 2 AS HOUR) UNION
    (SELECT 3 AS HOUR) UNION (SELECT 4 AS HOUR) UNION (SELECT 5 AS HOUR) UNION
    (SELECT 6 AS HOUR) UNION (SELECT 7 AS HOUR) UNION (SELECT 8 AS HOUR) UNION
    (SELECT 9 AS HOUR) UNION (SELECT 10 AS HOUR) UNION (SELECT 11 AS HOUR) UNION
    (SELECT 12 AS HOUR) UNION (SELECT 13 AS HOUR) UNION (SELECT 14 AS HOUR) UNION
    (SELECT 15 AS HOUR) UNION (SELECT 16 AS HOUR) UNION (SELECT 17 AS HOUR) UNION
    (SELECT 18 AS HOUR) UNION (SELECT 19 AS HOUR) UNION (SELECT 20 AS HOUR) UNION
    (SELECT 21 AS HOUR) UNION (SELECT 22 AS HOUR) UNION (SELECT 23 AS HOUR)
    )

SELECT
    A.hour,
    IFNULL(count, 0) AS count
FROM t2 AS A
LEFT JOIN t1 AS B
ON A.hour = B.hour