# 251031 금 PM 5:19

# 재귀함수로 time_table 생성 => WITH RECURSIVE _ AS (조건 설정)

WITH RECURSIVE 
time_table AS (
    SELECT 0 AS HOUR UNION
    SELECT hour+1 FROM time_table WHERE hour < 23
),
count_table AS (
    SELECT
        HOUR(datetime) AS hour,
        COUNT(*) AS COUNT
    FROM animal_outs AS a
    GROUP BY hour
)

SELECT
    a.HOUR,
    IFNULL(COUNT, 0) AS COUNT
FROM time_table AS a
LEFT JOIN count_table AS c
ON a.hour = c.hour

# WITH time_table AS (
#     SELECT 0 AS HOUR
#     UNION SELECT 1 AS HOUR UNION SELECT 2 AS HOUR
#     UNION SELECT 3 AS HOUR UNION SELECT 4 AS HOUR
#     UNION SELECT 5 AS HOUR UNION SELECT 6 AS HOUR
#     UNION SELECT 7 AS HOUR UNION SELECT 8 AS HOUR 
#     UNION SELECT 9 AS HOUR UNION SELECT 10 AS HOUR
#     UNION SELECT 11 AS HOUR UNION SELECT 12 AS HOUR
#     UNION SELECT 13 AS HOUR UNION SELECT 14 AS HOUR
#     UNION SELECT 15 AS HOUR UNION SELECT 16 AS HOUR
#     UNION SELECT 17 AS HOUR UNION SELECT 18 AS HOUR
#     UNION SELECT 19 AS HOUR UNION SELECT 20 AS HOUR
#     UNION SELECT 21 AS HOUR UNION SELECT 22 AS HOUR
#     UNION SELECT 23 AS HOUR
# ),