# 250403 목 PM 8:43

WITH out_list AS(
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE NAME is not null
)

SELECT
    NAME,
    DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM out_list) AND
      NAME is not null
ORDER BY DATETIME
LIMIT 3