# 250402 수 PM 5:32
/*
오답포인트) GROUP BY i.REST_ID 만 사용
=> 정확한 값을 보장하려면, GROUP BY 대상에 모든 컬럼을 넣거나,
서브쿼리로 따로 SCORE만 집계해서 JOIN하는 방식을 활용해야 함
*/

SELECT
    i.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO as i
JOIN REST_REVIEW as r
ON i.REST_ID = r.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY
    i.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC