# 250403 목 AM 12:19

WITH root_item AS (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID is NULL
)

SELECT
    ITEM_ID,
    ITEM_NAME
FROM ITEM_INFO
WHERE ITEM_ID in (SELECT ITEM_ID FROM root_item)
ORDER BY ITEM_ID