# 250330 일 AM 12:43 / CTE로 서브쿼리 분리

WITH 
    CODE_C AS (
        SELECT CODE
        FROM SKILLCODES
        WHERE NAME  = 'C#'
    ),
    CODE_P AS (
        SELECT CODE
        FROM SKILLCODES
        WHERE NAME = 'Python'
    )

SELECT
    ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE
    SKILL_CODE & (SELECT CODE FROM CODE_C)
    OR
    SKILL_CODE & (SELECT CODE FROM CODE_P)
ORDER BY ID