# 241012 토 AM 12:22

SELECT
    E.DEPT_ID,
    DEPT_NAME_EN,
    ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES AS E
JOIN HR_DEPARTMENT AS D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY
    E.DEPT_ID,
    DEPT_NAME_EN
ORDER BY AVG_SAL DESC