# 241011 금 PM 7:52

# 1. USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서
#     - WRITER_ID = USER_ID
# 2. 완료된 중고 거래의 총금액이 70만 원 이상인 사람의
#     - STATUS = "DONE"
#     - GROUP BY => SUM(PRICE)
# 3. 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요.
# 4. 결과는 총거래금액을 기준으로 오름차순 정렬

SELECT
    B.WRITER_ID,
    U.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
ON B.WRITER_ID = U.USER_ID
WHERE
    STATUS = "DONE"
GROUP BY
    B.WRITER_ID,
    U.NICKNAME
HAVING
    TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES