# 240927 금 AM 1:54

SELECT
    t.FLAVOR
FROM
    (SELECT
        FLAVOR,
        TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL
    SELECT
        FLAVOR,
        TOTAL_ORDER
    FROM JULY) AS t
GROUP BY t.FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3